"""fix supplier_info and customer_info PK

Revision ID: 808949279326
Revises: 50b594d07099
Create Date: 2025-06-19 13:02:14.736539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '808949279326'
down_revision: Union[str, Sequence[str], None] = '50b594d07099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customer_info', ['user_id'])
    op.create_unique_constraint(None, 'supplier_info', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_info', type_='unique')
    op.drop_constraint(None, 'customer_info', type_='unique')
    # ### end Alembic commands ###
