"""add user_id foreign key to tokens

Revision ID: a2c83124ee52
Revises: b7958d8fe2ef
Create Date: 2025-06-19 10:35:35.476283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c83124ee52'
down_revision: Union[str, Sequence[str], None] = 'b7958d8fe2ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tokens', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tokens', type_='foreignkey')
    op.drop_column('tokens', 'user_id')
    # ### end Alembic commands ###
